# Generated by Django 3.2.3 on 2021-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='direction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
