# Generated by Django 3.2.3 on 2021-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_images_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
