# Generated by Django 3.2.3 on 2021-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_images_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=225, null=True)),
                ('api_key', models.CharField(blank=True, max_length=225, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
